# Generated by Django 5.2.3 on 2025-06-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[("income", "Income"), ("expense", "Expense")],
                default="expense",
                max_length=7,
            ),
        ),
    ]
