# Generated by Django 5.2.3 on 2025-06-28 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_alter_budgetlimit_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetlimit',
            options={'verbose_name': 'Budget Limit', 'verbose_name_plural': 'Budget Limits'},
        ),
        migrations.AlterUniqueTogether(
            name='budgetlimit',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='budgetlimit',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='budgetlimit',
            name='limit_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Limit Amount'),
        ),
        migrations.AlterField(
            model_name='budgetlimit',
            name='period',
            field=models.CharField(choices=[('DAY', 'Daily'), ('WEEK', 'Weekly'), ('MONTH', 'Monthly')], max_length=10, verbose_name='Period'),
        ),
        migrations.AlterUniqueTogether(
            name='budgetlimit',
            unique_together={('user', 'category', 'period')},
        ),
    ]
