# Generated by Django 5.2.3 on 2026-02-20 20:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0008_alter_budgetlimit_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="budgetlimit",
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["user", "type"], name="transaction_user_id_4685bf_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="budgetlimit",
            constraint=models.UniqueConstraint(
                fields=("user", "category", "period"),
                name="unique_user_category_period",
            ),
        ),
    ]
